import React, { useState, useEffect } from 'react';
import { View, StyleSheet, Modal, ScrollView, Alert, TextInput as RNTextInput } from 'react-native';
import { TextInput, Button, Title, RadioButton, Text, Card } from 'react-native-paper';
import { projectsAPI, clientsAPI } from '../services/api';
import { useTheme } from '../contexts/ThemeContext';

interface DeadlineTaskModalProps {
  visible: boolean;
  onDismiss: () => void;
  onSave: (data: DeadlineTaskData) => void;
  onDelete?: () => void;
  date: Date;
  slotIndex: number;
  existingTask?: DeadlineTask | null;
}

export interface DeadlineTask {
  id: string;
  date: Date;
  slotIndex: number;
  clientId: string;
  description?: string;
  deadlineType: 'DEADLINE' | 'INTERNAL_DEADLINE' | 'MILESTONE';
  projectId?: string;
  isAutoGenerated: boolean;
  client?: {
    id: string;
    name: string;
  };
  project?: {
    id: string;
    name: string;
    projectNumber: string;
    description?: string;
  };
}

export interface DeadlineTaskData {
  clientId: string;
  description?: string;
  deadlineType: 'DEADLINE' | 'INTERNAL_DEADLINE' | 'MILESTONE';
  projectId?: string;
}

const DeadlineTaskModal: React.FC<DeadlineTaskModalProps> = ({
  visible,
  onDismiss,
  onSave,
  onDelete,
  date,
  slotIndex,
  existingTask,
}) => {
  const { currentColors } = useTheme();
  const [projects, setProjects] = useState<any[]>([]);
  const [filteredProjects, setFilteredProjects] = useState<any[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState('');
  const [projectSearch, setProjectSearch] = useState('');
  const [clients, setClients] = useState<any[]>([]);
  const [filteredClients, setFilteredClients] = useState<any[]>([]);
  const [selectedClientId, setSelectedClientId] = useState('');
  const [clientSearch, setClientSearch] = useState('');
  const [description, setDescription] = useState('');
  const [deadlineType, setDeadlineType] = useState<'DEADLINE' | 'INTERNAL_DEADLINE' | 'MILESTONE'>('DEADLINE');
  const [loading, setLoading] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  useEffect(() => {
    if (visible) {
      loadProjects();
      loadClients();

      // If editing existing task, populate form
      if (existingTask) {
        setSelectedProjectId(existingTask.projectId || '');
        setSelectedClientId(existingTask.clientId || '');
        setDescription(existingTask.description || '');
        setDeadlineType(existingTask.deadlineType);
        if (existingTask.project) {
          setProjectSearch(existingTask.project.description || existingTask.project.name);
        }
        if (existingTask.client) {
          setClientSearch(existingTask.client.name);
        }
      } else {
        // Reset form for new task
        setSelectedProjectId('');
        setSelectedClientId('');
        setProjectSearch('');
        setClientSearch('');
        setDescription('');
        setDeadlineType('DEADLINE');
      }
    }
  }, [visible, existingTask]);

  const loadProjects = async () => {
    try {
      const response = await projectsAPI.getAll();
      setProjects(response.data);
      setFilteredProjects(response.data);
    } catch (error) {
      console.error('Error loading projects:', error);
      Alert.alert('Error', 'Failed to load projects');
    }
  };

  const loadClients = async () => {
    try {
      const response = await clientsAPI.getAll();
      setClients(response.data);
      setFilteredClients(response.data);
    } catch (error) {
      console.error('Error loading clients:', error);
      Alert.alert('Error', 'Failed to load clients');
    }
  };

  const handleProjectSearch = (text: string) => {
    setProjectSearch(text);
    if (text.trim() === '') {
      setFilteredProjects(projects);
    } else {
      const filtered = projects.filter((project: any) => {
        const displayName = project.description || project.name;
        return displayName.toLowerCase().includes(text.toLowerCase());
      });
      setFilteredProjects(filtered);
    }
  };

  const handleProjectSelect = (project: any) => {
    setSelectedProjectId(project.id);
    setProjectSearch(project.description || project.name);
    setFilteredProjects([]);
    // Auto-select client from project
    setSelectedClientId(project.clientId);
    const client = clients.find((c) => c.id === project.clientId);
    if (client) {
      setClientSearch(client.name);
    }
  };

  const handleClientSearch = (text: string) => {
    setClientSearch(text);
    if (text.trim() === '') {
      setFilteredClients(clients);
    } else {
      const filtered = clients.filter((client: any) =>
        client.name.toLowerCase().includes(text.toLowerCase())
      );
      setFilteredClients(filtered);
    }
  };

  const handleClientSelect = (client: any) => {
    setSelectedClientId(client.id);
    setClientSearch(client.name);
    setFilteredClients([]);
  };

  const handleSubmit = () => {
    // For DEADLINE type, project is required
    if (deadlineType === 'DEADLINE' && !selectedProjectId) {
      Alert.alert('Error', 'Please select a project for Deadline type');
      return;
    }

    // For INTERNAL_DEADLINE and MILESTONE, either project or client is required
    if ((deadlineType === 'INTERNAL_DEADLINE' || deadlineType === 'MILESTONE') && !selectedProjectId && !selectedClientId) {
      Alert.alert('Error', 'Please select either a project or a client');
      return;
    }

    let clientId = selectedClientId;

    // If project is selected, get client from project
    if (selectedProjectId) {
      const selectedProject = projects.find((p) => p.id === selectedProjectId);
      if (!selectedProject) {
        Alert.alert('Error', 'Selected project not found');
        return;
      }
      clientId = selectedProject.clientId;
    }

    // Ensure we have a clientId
    if (!clientId) {
      Alert.alert('Error', 'Client is required');
      return;
    }

    onSave({
      clientId,
      projectId: selectedProjectId || undefined,
      description: description.trim() || undefined,
      deadlineType,
    });

    onDismiss();
  };

  const handleDeleteClick = () => {
    console.log('[DeadlineTaskModal] Delete button pressed', { existingTask, deadlineType, onDelete: !!onDelete });
    setShowDeleteConfirm(true);
  };

  const handleDeleteConfirm = async () => {
    console.log('[DeadlineTaskModal] Delete confirmed, calling onDelete');
    if (onDelete) {
      try {
        setLoading(true);
        await onDelete();
        console.log('[DeadlineTaskModal] Delete completed successfully');
        setShowDeleteConfirm(false);
        onDismiss();
      } catch (error) {
        console.error('[DeadlineTaskModal] Delete failed:', error);
        setLoading(false);
        setShowDeleteConfirm(false);
      }
    } else {
      console.error('[DeadlineTaskModal] onDelete is not defined!');
      setShowDeleteConfirm(false);
    }
  };

  const handleDeleteCancel = () => {
    setShowDeleteConfirm(false);
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={onDismiss}
    >
      <View style={styles.modalOverlay}>
        <View
          style={[
            styles.modalContainer,
            { backgroundColor: currentColors.background.bg700 }
          ]}
        >
          <ScrollView>
            <Card style={{ backgroundColor: currentColors.background.bg600, borderRadius: 8 }}>
              <Card.Content>
              <Title style={{ color: currentColors.text }}>
                {existingTask ? 'Edit Deadline / Milestone' : 'Add Deadline / Milestone'}
              </Title>

              <Text style={[styles.dateText, { color: currentColors.textSecondary }]}>
                {date.toLocaleDateString()} - Slot {slotIndex + 1}
              </Text>

              {/* Deadline Type */}
              <View style={styles.section}>
                <Text style={[styles.label, { color: currentColors.text }]}>Type *</Text>

                <RadioButton.Group onValueChange={value => setDeadlineType(value as any)} value={deadlineType}>
                  <View style={styles.radioItem}>
                    <RadioButton value="DEADLINE" />
                    <Text style={{ color: currentColors.text }}>Deadline</Text>
                  </View>

                  <View style={styles.radioItem}>
                    <RadioButton value="INTERNAL_DEADLINE" />
                    <Text style={{ color: currentColors.text }}>Internal Deadline</Text>
                  </View>

                  <View style={styles.radioItem}>
                    <RadioButton value="MILESTONE" />
                    <Text style={{ color: currentColors.text }}>Milestone</Text>
                  </View>
                </RadioButton.Group>
              </View>

              {/* Project Selection */}
              <View style={styles.section}>
                <Text style={[styles.label, { color: currentColors.text }]}>
                  Project (by common name) {deadlineType === 'DEADLINE' ? '*' : '(optional)'}
                </Text>
                <RNTextInput
                  style={[
                    styles.searchInput,
                    {
                      backgroundColor: currentColors.background.bg700,
                      color: currentColors.text,
                      borderColor: currentColors.border,
                    }
                  ]}
                  placeholder="Search by common name..."
                  placeholderTextColor={currentColors.textTertiary}
                  value={projectSearch}
                  onChangeText={handleProjectSearch}
                  onFocus={() => setFilteredProjects(projects)}
                />

                {filteredProjects.length > 0 && projectSearch !== '' && (
                  <ScrollView
                    style={[
                      styles.projectList,
                      {
                        backgroundColor: currentColors.background.bg500,
                        borderColor: currentColors.border,
                      }
                    ]}
                    nestedScrollEnabled
                  >
                    {filteredProjects.map((project) => (
                      <Button
                        key={project.id}
                        mode="text"
                        onPress={() => handleProjectSelect(project)}
                        style={styles.projectItem}
                        contentStyle={{ justifyContent: 'flex-start' }}
                        labelStyle={{ color: currentColors.text, textAlign: 'left' }}
                      >
                        {project.description || project.name}
                      </Button>
                    ))}
                  </ScrollView>
                )}
              </View>

              {/* Client Selection - Only show if no project selected and type is not DEADLINE */}
              {!selectedProjectId && deadlineType !== 'DEADLINE' && (
                <View style={styles.section}>
                  <Text style={[styles.label, { color: currentColors.text }]}>Client *</Text>
                  <RNTextInput
                    style={[
                      styles.searchInput,
                      {
                        backgroundColor: currentColors.background.bg700,
                        color: currentColors.text,
                        borderColor: currentColors.border,
                      }
                    ]}
                    placeholder="Search by client name..."
                    placeholderTextColor={currentColors.textTertiary}
                    value={clientSearch}
                    onChangeText={handleClientSearch}
                    onFocus={() => setFilteredClients(clients)}
                  />

                  {filteredClients.length > 0 && clientSearch !== '' && (
                    <ScrollView
                      style={[
                        styles.projectList,
                        {
                          backgroundColor: currentColors.background.bg500,
                          borderColor: currentColors.border,
                        }
                      ]}
                      nestedScrollEnabled
                    >
                      {filteredClients.map((client) => (
                        <Button
                          key={client.id}
                          mode="text"
                          onPress={() => handleClientSelect(client)}
                          style={styles.projectItem}
                          contentStyle={{ justifyContent: 'flex-start' }}
                          labelStyle={{ color: currentColors.text, textAlign: 'left' }}
                        >
                          {client.name}
                        </Button>
                      ))}
                    </ScrollView>
                  )}
                </View>
              )}

              {/* Task Description */}
              <TextInput
                label="Task Description (Optional)"
                value={description}
                onChangeText={setDescription}
                mode="outlined"
                multiline
                numberOfLines={2}
                style={styles.input}
              />

              {/* Delete Confirmation */}
              {showDeleteConfirm && (
                <View style={[styles.confirmContainer, { backgroundColor: currentColors.background.bg500, borderColor: currentColors.secondary }]}>
                  <Text style={[styles.confirmText, { color: currentColors.text }]}>
                    Are you sure you want to delete this deadline/milestone?
                  </Text>
                  <View style={styles.confirmButtons}>
                    <Button
                      mode="outlined"
                      onPress={handleDeleteCancel}
                      disabled={loading}
                      style={styles.confirmButton}
                    >
                      Cancel
                    </Button>
                    <Button
                      mode="contained"
                      onPress={handleDeleteConfirm}
                      loading={loading}
                      disabled={loading}
                      style={styles.confirmButton}
                      buttonColor={currentColors.secondary}
                    >
                      Delete
                    </Button>
                  </View>
                </View>
              )}

              {/* Action Buttons */}
              <View style={styles.buttonContainer}>
                {existingTask && onDelete && !showDeleteConfirm && (
                  <Button
                    mode="outlined"
                    onPress={handleDeleteClick}
                    disabled={loading}
                    style={styles.deleteButton}
                    textColor={currentColors.secondary}
                  >
                    Delete
                  </Button>
                )}

                <View style={styles.rightButtonGroup}>
                  <Button
                    mode="outlined"
                    onPress={onDismiss}
                    style={styles.button}
                    disabled={loading || showDeleteConfirm}
                  >
                    Cancel
                  </Button>

                  <Button
                    mode="contained"
                    onPress={handleSubmit}
                    loading={loading}
                    disabled={loading || showDeleteConfirm}
                    style={styles.button}
                  >
                    {existingTask ? 'Save' : 'Create'}
                  </Button>
                </View>
              </View>
            </Card.Content>
          </Card>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxWidth: 600,
    maxHeight: '80%',
  },
  dateText: {
    fontSize: 14,
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  searchInput: {
    borderWidth: 1,
    borderRadius: 4,
    padding: 12,
    fontSize: 16,
    marginBottom: 8,
  },
  projectList: {
    maxHeight: 200,
    borderWidth: 1,
    borderRadius: 4,
    marginTop: 4,
  },
  projectItem: {
    justifyContent: 'flex-start',
    borderRadius: 0,
  },
  input: {
    marginBottom: 0,
  },
  radioItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  buttonContainer: {
    marginTop: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deleteButton: {
    minWidth: 100,
  },
  rightButtonGroup: {
    flexDirection: 'row',
    gap: 10,
  },
  button: {
    minWidth: 100,
  },
  confirmContainer: {
    padding: 16,
    marginVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
  },
  confirmText: {
    fontSize: 14,
    marginBottom: 12,
    textAlign: 'center',
  },
  confirmButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  confirmButton: {
    minWidth: 100,
  },
});

export default DeadlineTaskModal;
