import React, { useState, useEffect } from 'react';
import { View, StyleSheet, Modal, ScrollView, TextInput as RNTextInput, KeyboardAvoidingView, Platform, TouchableWithoutFeedback, Keyboard } from 'react-native';
import { TextInput, Button, Title, RadioButton, Text, Card, IconButton } from 'react-native-paper';
import { HugeiconsIcon } from '@hugeicons/react-native';
import { Search01Icon, Cancel01Icon } from '@hugeicons/core-free-icons';
import { projectsAPI, clientsAPI } from '../services/api';
import { useTheme } from '../contexts/ThemeContext';
import { CustomDialog } from './CustomDialog';

interface DeadlineTaskModalProps {
  visible: boolean;
  onDismiss: () => void;
  onSave: (data: DeadlineTaskData) => void;
  onDelete?: () => void;
  date: Date;
  slotIndex: number;
  existingTask?: DeadlineTask | null;
}

export interface DeadlineTask {
  id: string;
  date: Date;
  slotIndex: number;
  clientId?: string;
  description?: string;
  deadlineType: 'DEADLINE' | 'INTERNAL_DEADLINE' | 'MILESTONE';
  projectId?: string;
  isAutoGenerated: boolean;
  client?: {
    id: string;
    name: string;
  };
  project?: {
    id: string;
    name: string;
    projectNumber: string;
    description?: string;
  };
}

export interface DeadlineTaskData {
  clientId?: string;
  description?: string;
  deadlineType: 'DEADLINE' | 'INTERNAL_DEADLINE' | 'MILESTONE';
  projectId?: string;
}

const DeadlineTaskModal: React.FC<DeadlineTaskModalProps> = ({
  visible,
  onDismiss,
  onSave,
  onDelete,
  date,
  slotIndex,
  existingTask,
}) => {
  const { currentColors } = useTheme();
  const [projects, setProjects] = useState<any[]>([]);
  const [filteredProjects, setFilteredProjects] = useState<any[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState('');
  const [projectSearch, setProjectSearch] = useState('');
  const [clients, setClients] = useState<any[]>([]);
  const [filteredClients, setFilteredClients] = useState<any[]>([]);
  const [selectedClientId, setSelectedClientId] = useState('');
  const [clientSearch, setClientSearch] = useState('');
  const [description, setDescription] = useState('');
  const [deadlineType, setDeadlineType] = useState<'DEADLINE' | 'INTERNAL_DEADLINE' | 'MILESTONE'>('DEADLINE');
  const [loading, setLoading] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  // Dialog state
  const [dialogVisible, setDialogVisible] = useState(false);
  const [dialogTitle, setDialogTitle] = useState('');
  const [dialogMessage, setDialogMessage] = useState('');
  const [dialogButtons, setDialogButtons] = useState<any[]>([]);

  useEffect(() => {
    if (visible) {
      // Reset loading state when modal opens
      setLoading(false);
      setShowDeleteConfirm(false);

      loadProjects();
      loadClients();

      // If editing existing task, populate form
      if (existingTask) {
        setSelectedProjectId(existingTask.projectId || '');
        setSelectedClientId(existingTask.clientId || '');
        setDescription(existingTask.description || '');
        setDeadlineType(existingTask.deadlineType);
        if (existingTask.project) {
          setProjectSearch(existingTask.project.description || existingTask.project.name);
        }
        if (existingTask.client) {
          setClientSearch(existingTask.client.name);
        }
      } else {
        // Reset form for new task
        setSelectedProjectId('');
        setSelectedClientId('');
        setProjectSearch('');
        setClientSearch('');
        setDescription('');
        setDeadlineType('DEADLINE');
      }
    }
  }, [visible, existingTask]);

  const loadProjects = async () => {
    try {
      const response = await projectsAPI.getAll();
      setProjects(response.data);
      setFilteredProjects(response.data);
    } catch (error) {
      console.error('Error loading projects:', error);
      setDialogTitle('Error');
      setDialogMessage('Failed to load projects');
      setDialogButtons([{ text: 'OK', onPress: () => setDialogVisible(false) }]);
      setDialogVisible(true);
    }
  };

  const loadClients = async () => {
    try {
      const response = await clientsAPI.getAll();
      setClients(response.data);
      setFilteredClients(response.data);
    } catch (error) {
      console.error('Error loading clients:', error);
      setDialogTitle('Error');
      setDialogMessage('Failed to load clients');
      setDialogButtons([{ text: 'OK', onPress: () => setDialogVisible(false) }]);
      setDialogVisible(true);
    }
  };

  const handleProjectSearch = (text: string) => {
    setProjectSearch(text);
    if (text.trim() === '') {
      setFilteredProjects([]);
    } else {
      const filtered = projects.filter((project: any) => {
        const displayName = project.description || project.name;
        return displayName.toLowerCase().includes(text.toLowerCase());
      });
      setFilteredProjects(filtered);
    }
  };

  const handleProjectSelect = (project: any) => {
    setSelectedProjectId(project.id);
    setProjectSearch(project.description || project.name);
    setFilteredProjects([]);
    // Auto-select client from project
    setSelectedClientId(project.clientId);
    const client = clients.find((c) => c.id === project.clientId);
    if (client) {
      setClientSearch(client.name);
    }
  };

  const handleClientSearch = (text: string) => {
    setClientSearch(text);
    if (text.trim() === '') {
      setFilteredClients(clients);
    } else {
      const filtered = clients.filter((client: any) =>
        client.name.toLowerCase().includes(text.toLowerCase())
      );
      setFilteredClients(filtered);
    }
  };

  const handleClientSelect = (client: any) => {
    setSelectedClientId(client.id);
    setClientSearch(client.name);
    setFilteredClients([]);
  };

  const handleSubmit = () => {
    // Require either a description or project
    if (!description.trim() && !selectedProjectId) {
      setDialogTitle('Error');
      setDialogMessage('Please provide either a description or select a project');
      setDialogButtons([{ text: 'OK', onPress: () => setDialogVisible(false) }]);
      setDialogVisible(true);
      return;
    }

    let clientId: string | undefined = undefined;

    // If project is selected, get clientId from project
    if (selectedProjectId) {
      const selectedProject = projects.find((p) => p.id === selectedProjectId);
      if (!selectedProject) {
        setDialogTitle('Error');
        setDialogMessage('Selected project not found');
        setDialogButtons([{ text: 'OK', onPress: () => setDialogVisible(false) }]);
        setDialogVisible(true);
        return;
      }
      clientId = selectedProject.clientId;
    }

    // Set loading state and close modal immediately
    // The save operation will complete in the background (non-blocking for UI)
    setLoading(true);
    onDismiss();

    // Execute save in background
    onSave({
      clientId,
      projectId: selectedProjectId || undefined,
      description: description.trim() || undefined,
      deadlineType,
    });
  };

  const handleDeleteClick = () => {

    setShowDeleteConfirm(true);
  };

  const handleDeleteConfirm = async () => {

    if (onDelete) {
      try {
        setLoading(true);

        // Close modal immediately - don't wait for Outlook sync (8 second timeout)
        // The delete operation will complete in the background
        setShowDeleteConfirm(false);
        onDismiss();

        // Execute delete in background (non-blocking for UI)
        onDelete().catch((error) => {
          console.error('[DeadlineTaskModal] Delete failed:', error);
        });

      } catch (error) {
        console.error('[DeadlineTaskModal] Delete failed:', error);
        setLoading(false);
        setShowDeleteConfirm(false);
      }
    } else {
      console.error('[DeadlineTaskModal] onDelete is not defined!');
      setShowDeleteConfirm(false);
    }
  };

  const handleDeleteCancel = () => {
    setShowDeleteConfirm(false);
  };

  return (
    <Modal
      visible={visible}
      transparent
      animationType="fade"
      onRequestClose={onDismiss}
    >
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={styles.keyboardAvoid}
      >
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <View style={styles.modalOverlay}>
            <TouchableWithoutFeedback>
              <View
                style={[
                  styles.modalContainer,
                  { backgroundColor: currentColors.background.bg700 }
                ]}
              >
                <ScrollView
                  contentContainerStyle={{ paddingBottom: 0 }}
                  keyboardShouldPersistTaps="handled"
                  showsVerticalScrollIndicator={true}
                >
                  <Card style={{ backgroundColor: currentColors.background.bg600, borderRadius: 8, elevation: 0, borderWidth: 0 }}>
                    <Card.Content style={{ paddingBottom: 0 }}>
              <View style={styles.modalHeader}>
                <View style={{ flex: 1 }}>
                  <Title style={{ color: currentColors.text }}>
                    {existingTask ? 'Edit Deadline / Milestone' : 'Add Deadline / Milestone'}
                  </Title>
                  <Text style={[styles.dateText, { color: currentColors.textSecondary }]}>
                    {date.toLocaleDateString()} - Slot {slotIndex + 1}
                  </Text>
                </View>
                <IconButton
                  icon={() => <HugeiconsIcon icon={Cancel01Icon} size={24} color={currentColors.text} />}
                  onPress={onDismiss}
                />
              </View>


              {/* Deadline Type */}
              <View style={styles.section}>
                <Text style={[styles.label, { color: currentColors.text }]}>Type *</Text>

                <RadioButton.Group onValueChange={value => setDeadlineType(value as any)} value={deadlineType}>
                  <View style={styles.radioItem}>
                    <RadioButton value="DEADLINE" />
                    <Text style={{ color: currentColors.text }}>Deadline</Text>
                  </View>

                  <View style={styles.radioItem}>
                    <RadioButton value="INTERNAL_DEADLINE" />
                    <Text style={{ color: currentColors.text }}>Internal Deadline</Text>
                  </View>

                  <View style={styles.radioItem}>
                    <RadioButton value="MILESTONE" />
                    <Text style={{ color: currentColors.text }}>Milestone</Text>
                  </View>
                </RadioButton.Group>
              </View>

              {/* Project Selection */}
              <View style={styles.section}>
                <Text style={[styles.label, { color: currentColors.text }]}>
                  Project (by common name) {deadlineType === 'DEADLINE' ? '*' : '(optional)'}
                </Text>
                <View style={[styles.searchInputContainer, { backgroundColor: currentColors.background.bg700, borderColor: currentColors.border }]}>
                  <HugeiconsIcon icon={Search01Icon} size={20} color={currentColors.icon} />
                  <RNTextInput
                    style={[
                      styles.searchInput,
                      {
                        color: currentColors.text,
                      }
                    ]}
                    placeholder="Search by common name..."
                    placeholderTextColor={currentColors.textTertiary}
                    value={projectSearch}
                    onChangeText={handleProjectSearch}
                  />
                </View>

                {filteredProjects.length > 0 && projectSearch.trim() !== '' && (
                  <ScrollView
                    style={[
                      styles.projectList,
                      {
                        backgroundColor: currentColors.background.bg500,
                        borderColor: currentColors.border,
                      }
                    ]}
                    nestedScrollEnabled
                  >
                    {filteredProjects.map((project) => (
                      <Button
                        key={project.id}
                        mode="text"
                        onPress={() => handleProjectSelect(project)}
                        style={styles.projectItem}
                        contentStyle={{ justifyContent: 'flex-start' }}
                        labelStyle={{ color: currentColors.text, textAlign: 'left' }}
                      >
                        {project.description || project.name}
                      </Button>
                    ))}
                  </ScrollView>
                )}
              </View>

              {/* Task Description */}
              <TextInput
                label="Task Description (Optional)"
                value={description}
                onChangeText={setDescription}
                mode="outlined"
                multiline
                numberOfLines={2}
                style={[styles.input, { marginBottom: 20 }]}
                outlineStyle={{ borderWidth: 1 }}
              />

              {/* Delete Confirmation */}
              {showDeleteConfirm && (
                <View style={[styles.confirmContainer, { backgroundColor: currentColors.background.bg500, borderColor: currentColors.secondary }]}>
                  <Text style={[styles.confirmText, { color: currentColors.text }]}>
                    Are you sure you want to delete this deadline/milestone?
                  </Text>
                  <View style={styles.confirmButtons}>
                    <Button
                      mode="outlined"
                      onPress={handleDeleteCancel}
                      disabled={loading}
                      style={styles.confirmButton}
                    >
                      Cancel
                    </Button>
                    <Button
                      mode="contained"
                      onPress={handleDeleteConfirm}
                      loading={loading}
                      disabled={loading}
                      style={styles.confirmButton}
                      buttonColor={currentColors.secondary}
                    >
                      Delete
                    </Button>
                  </View>
                </View>
              )}

              {/* Action Buttons */}
              <View style={styles.buttonContainer}>
                {existingTask && onDelete && !showDeleteConfirm && (
                  <Button
                    mode="outlined"
                    onPress={handleDeleteClick}
                    disabled={loading}
                    style={styles.deleteButton}
                    textColor={currentColors.secondary}
                  >
                    Delete
                  </Button>
                )}

                <View style={styles.rightButtonGroup}>
                  <Button
                    mode="outlined"
                    onPress={onDismiss}
                    style={styles.button}
                    disabled={loading || showDeleteConfirm}
                  >
                    Cancel
                  </Button>

                  <Button
                    mode="contained"
                    onPress={handleSubmit}
                    loading={loading}
                    disabled={loading || showDeleteConfirm}
                    style={styles.button}
                  >
                    {existingTask ? 'Save' : 'Create'}
                  </Button>
                </View>
              </View>
                    </Card.Content>
                  </Card>
                </ScrollView>
              </View>
            </TouchableWithoutFeedback>
          </View>
        </TouchableWithoutFeedback>
      </KeyboardAvoidingView>

      <CustomDialog
        visible={dialogVisible}
        title={dialogTitle}
        message={dialogMessage}
        buttons={dialogButtons}
        onDismiss={() => setDialogVisible(false)}
      />
    </Modal>
  );
};

const styles = StyleSheet.create({
  keyboardAvoid: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Platform.select({
      ios: 40,
      android: 20,
      web: 20,
    }),
    paddingHorizontal: 10,
  },
  modalContainer: {
    width: '100%',
    minWidth: 280,
    maxWidth: 600,
    maxHeight: '85%',
    borderRadius: 12,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  dateText: {
    fontSize: 14,
    marginBottom: 10,
  },
  section: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 12,
    marginBottom: 8,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    padding: 12,
    fontSize: 16,
  },
  projectList: {
    maxHeight: 200,
    borderWidth: 1,
    borderRadius: 4,
    marginTop: 4,
  },
  projectItem: {
    justifyContent: 'flex-start',
    borderRadius: 0,
  },
  input: {
    marginBottom: 15,
  },
  radioItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  buttonContainer: {
    marginTop: 15,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deleteButton: {
    minWidth: 100,
  },
  rightButtonGroup: {
    flexDirection: 'row',
    gap: 10,
  },
  button: {
    minWidth: 100,
  },
  confirmContainer: {
    padding: 16,
    marginVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
  },
  confirmText: {
    fontSize: 14,
    marginBottom: 12,
    textAlign: 'center',
  },
  confirmButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  confirmButton: {
    minWidth: 100,
  },
});

export default DeadlineTaskModal;
