import prisma from '../src/config/database';

async function main() {
  // Check deadline tasks for Dec 11 and Dec 12
  const dec11 = new Date('2025-12-11');
  dec11.setHours(0, 0, 0, 0);

  const dec12 = new Date('2025-12-12');
  dec12.setHours(0, 0, 0, 0);

  const deadlineTasks = await prisma.deadlineTask.findMany({
    where: {
      OR: [
        { date: dec11 },
        { date: dec12 },
      ]
    },
    include: {
      client: true,
      creator: true,
    },
    orderBy: {
      date: 'asc',
    }
  });

  console.log(`Found ${deadlineTasks.length} deadline tasks for Dec 11-12:\n`);

  deadlineTasks.forEach((task, i) => {
    console.log(`${i + 1}. ${task.date.toISOString().split('T')[0]} - Slot ${task.slotIndex}`);
    console.log(`   Description: ${task.description}`);
    console.log(`   Client: ${task.client.name}`);
    console.log(`   Type: ${task.deadlineType}`);
    console.log(`   Auto-generated: ${task.isAutoGenerated}`);
    console.log(`   Project ID: ${task.projectId || 'None'}`);
    console.log('');
  });

  // Also check P555's due date
  const p555 = await prisma.project.findFirst({
    where: {
      name: 'P555',
    }
  });

  if (p555) {
    console.log('P555 due date:', p555.dueDate);
    console.log('P555 due date normalized:', p555.dueDate ? new Date(p555.dueDate).toISOString() : 'Not set');
  }
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
