import prisma from '../src/config/database';

async function main() {
  // Find P555
  const project = await prisma.project.findFirst({
    where: {
      name: 'P555'
    }
  });

  if (!project) {
    console.log('Project P555 not found');
    return;
  }

  console.log('Found project P555:', {
    id: project.id,
    name: project.name,
    dueDate: project.dueDate,
    clientId: project.clientId,
  });

  // Create deadline for Dec 12
  const dueDate = new Date('2025-12-12');
  dueDate.setHours(0, 0, 0, 0);

  // Check existing tasks on Dec 12
  const existingTasksOnDate = await prisma.deadlineTask.findMany({
    where: {
      date: dueDate,
    }
  });

  console.log(`\nExisting tasks on Dec 12: ${existingTasksOnDate.length}`);

  // Find available slot
  const usedSlots = new Set(existingTasksOnDate.map(t => t.slotIndex));
  let availableSlot = 0;
  if (usedSlots.has(0)) {
    availableSlot = 1;
    if (usedSlots.has(1)) {
      console.log('Both slots occupied!');
      return;
    }
  }

  console.log(`Creating deadline in slot ${availableSlot}...`);

  // Create the deadline task
  const deadlineTask = await prisma.deadlineTask.create({
    data: {
      date: dueDate,
      slotIndex: availableSlot,
      clientId: project.clientId,
      description: project.name,
      deadlineType: 'DEADLINE',
      projectId: project.id,
      isAutoGenerated: true,
      createdBy: project.createdBy,
    },
    include: {
      client: true,
    }
  });

  console.log('\n✅ Deadline task created successfully!');
  console.log({
    id: deadlineTask.id,
    date: deadlineTask.date.toISOString().split('T')[0],
    slotIndex: deadlineTask.slotIndex,
    client: deadlineTask.client.name,
    description: deadlineTask.description,
  });

  console.log('\nThe deadline should now appear in the Planning screen on Dec 12. Please refresh the planning screen.');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
