import prisma from '../src/config/database';

async function main() {
  console.log('Finding all projects with due dates...');

  const projectsWithDueDates = await prisma.project.findMany({
    where: {
      dueDate: {
        not: null,
      },
    },
    include: {
      deadlineTasks: {
        where: {
          isAutoGenerated: true,
        },
      },
    },
  });

  console.log(`Found ${projectsWithDueDates.length} projects with due dates`);

  for (const project of projectsWithDueDates) {
    const currentDueDate = project.dueDate!;
    console.log(`\nProject: ${project.name} (${project.projectNumber})`);
    console.log(`Current due date: ${currentDueDate.toISOString()}`);
    console.log(`Current due date (local): ${currentDueDate.toString()}`);

    // Check if the date looks like it has a timezone offset issue
    // If the hours are not 0, it's likely affected by timezone conversion
    const hours = currentDueDate.getUTCHours();

    if (hours !== 0) {
      // Calculate what the intended date was (add back the timezone offset)
      const year = currentDueDate.getUTCFullYear();
      const month = currentDueDate.getUTCMonth();
      const day = currentDueDate.getUTCDate();

      // Create a proper UTC date at midnight
      const correctedDate = new Date(Date.UTC(year, month, day, 0, 0, 0, 0));

      console.log(`Corrected due date: ${correctedDate.toISOString()}`);

      // Update the project
      await prisma.project.update({
        where: { id: project.id },
        data: {
          dueDate: correctedDate,
        },
      });

      // Update associated deadline tasks
      if (project.deadlineTasks.length > 0) {
        for (const task of project.deadlineTasks) {
          console.log(`Updating deadline task from ${task.date.toISOString()} to ${correctedDate.toISOString()}`);

          await prisma.deadlineTask.update({
            where: { id: task.id },
            data: {
              date: correctedDate,
            },
          });
        }
      }

      console.log(`✅ Updated ${project.name}`);
    } else {
      console.log(`✓ Already correct (UTC midnight)`);
    }
  }

  console.log('\n✅ All project due dates fixed!');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
