import prisma from '../src/config/database';

async function main() {
  // Find project P555
  const project = await prisma.project.findFirst({
    where: {
      projectNumber: 'P555'
    },
    include: {
      client: true,
      creator: true,
    }
  });

  if (!project) {
    console.log('Project P555 not found');
    return;
  }

  console.log('Found project:', {
    id: project.id,
    name: project.name,
    projectNumber: project.projectNumber,
    dueDate: project.dueDate,
    clientId: project.clientId,
    clientName: project.client.name,
  });

  // Check if deadline task already exists
  const existingDeadline = await prisma.deadlineTask.findFirst({
    where: {
      projectId: project.id,
      isAutoGenerated: true,
    }
  });

  if (existingDeadline) {
    console.log('Existing deadline task found:', existingDeadline);
  } else {
    console.log('No existing deadline task found');
  }

  // Create deadline for Dec 12, 2025
  const dueDate = new Date('2025-12-12');
  dueDate.setHours(0, 0, 0, 0);

  // Check existing tasks on that date
  const existingTasksOnDate = await prisma.deadlineTask.findMany({
    where: {
      date: dueDate,
    }
  });

  console.log(`\nTasks on ${dueDate.toISOString().split('T')[0]}:`, existingTasksOnDate.length);
  existingTasksOnDate.forEach((task, i) => {
    console.log(`  ${i + 1}. Slot ${task.slotIndex}: ${task.description} (${task.deadlineType})`);
  });

  // Find available slot
  const usedSlots = new Set(existingTasksOnDate.map(t => t.slotIndex));
  let availableSlot = 0;
  if (usedSlots.has(0)) {
    availableSlot = 1;
    if (usedSlots.has(1)) {
      console.log('\nBoth slots occupied on this date!');
      return;
    }
  }

  console.log(`\nAvailable slot: ${availableSlot}`);

  // Create the deadline task
  const deadlineTask = await prisma.deadlineTask.create({
    data: {
      date: dueDate,
      slotIndex: availableSlot,
      clientId: project.clientId,
      description: project.name,
      deadlineType: 'DEADLINE',
      projectId: project.id,
      isAutoGenerated: true,
      createdBy: project.createdBy,
    },
    include: {
      client: true,
    }
  });

  console.log('\nDeadline task created:', {
    id: deadlineTask.id,
    date: deadlineTask.date,
    slotIndex: deadlineTask.slotIndex,
    client: deadlineTask.client.name,
    description: deadlineTask.description,
    deadlineType: deadlineTask.deadlineType,
    isAutoGenerated: deadlineTask.isAutoGenerated,
  });

  console.log('\nSuccess! The deadline should now appear in the Planning screen on Dec 12.');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
